language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install: 
    - python setup.py install
    - pip install nose flake8 pep8-naming
before_script:
    - flake8 mintapi
# command to run tests
script: nosetests
